### ISSUE TITLE
StatProfileHTML forces downgrade to DataStructures@v0.17.20

### ISSUE THREAD

**Issue by petvana** [tkluck/StatProfilerHTML.jl#23]
I propose to update `Project.toml` to enable DataStructures@v0.18 in compat.

**Comment by petvana** [comment]
Re-opening until new patch version is released.

**Comment by tkluck** [comment]
Should have been released by now. Feel free to reopen if the issue isn't resolved.

**Comment by gsoleilhac** [comment]
It still downgrades DataStructures to 0.17 for me, I think it is due to HAML which depends on DataStructures@v0.17

> (@v1.7) pkg> add StatProfilerHTML@1.3
   Resolving package versions...
    Updating `C:\Users\Gauthier\.julia\environments\v1.7\Project.toml`
  [864edb3b] ↓ DataStructures v0.18.10 ⇒ v0.17.20
  [4076af6c] ↓ JuMP v0.21.10 ⇒ v0.21.4
  [a8a75453] ↑ StatProfilerHTML v1.0.0 ⇒ v1.3.0
    Updating `C:\Users\Gauthier\.julia\environments\v1.7\Manifest.toml`
  [864edb3b] ↓ DataStructures v0.18.10 ⇒ v0.17.20
  [0bc81568] + HAML v0.3.4
  [4076af6c] ↓ JuMP v0.21.10 ⇒ v0.21.4
  [a8a75453] ↑ StatProfilerHTML v1.0.0 ⇒ v1.3.0

**Comment by tkluck** [comment]
Thanks for noticing @gsoleilhac . This should be resolved by HAML v0.3.5.
