### ISSUE TITLE
Color for type unstable methods

### ISSUE THREAD

**Issue by tpapp** [tkluck/StatProfilerHTML.jl#9]
[ProfileView.jl](https://github.com/timholy/ProfileView.jl) uses red in the flamegraph for type unstable functions, which helps focus optimization effort. Does StatProfilerHTML.jl do something like this, and if not, could it? It would be very useful.

**Comment by tkluck** [comment]
Love the suggestion!

Currently, the Julia code does not distinguish between different methods of the same function in what it sends to the Perl executable. Also, I think that Perl lets the rendering of the flamegraph be handled by Javascript in the browser.

So that means we'd first have to separate methods on Julia's side, and pass information about whether its type-stable from there. Then adapt Perl + Javascript to handle that extra information.

Certainly possible, but I'm not sure I'll get to it very soon. Will happily provide pointers and/or accept pull requests, though!

**Comment by NHDaly** [comment]
Here's how it was implemented in that package, as far as i can tell: https://github.com/timholy/ProfileView.jl/pull/77

The trouble is that this package currently writes out the traces one at a time to the perl tool, but the julia itself never builds up an understanding of the profile tree. So I'm not sure if the julia would even be _able_ to know if a function calls `jl_invoke`.

**Comment by tkluck** [comment]
Closing this as this can be merged with ProfileSVG in the not-too-distant future.
